name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, uat ]
  pull_request:
    branches: [ main, dev, uat ]

jobs:
  terraform-build-deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Determine environment based on branch
      - name : Terraform env
        run: |
          case "${{ github.ref_name }}" in
            main)
              echo "TF_ENV=prod" >> $GITHUB_ENV
              ;;
            uat)
              echo "TF_ENV=uat" >> $GITHUB_ENV
              ;;
            dev)
              echo "TF_ENV=dev" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported branch: ${{ github.ref_name }}"
              exit 1
              ;;
          esac

          echo "TF_DIR=terraform_env/$TF_ENV" >> $GITHUB_ENV

      # Terraform Init
      - name: Terraform Init
        working-directory: ./${{ env.TF_DIR }}
        run: |
          terraform init -reconfigure \
            -backend-config=../../backend-config/${{ env.TF_ENV }}.hcl

      - name: Terraform Validate
        working-directory: ./${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./${{ env.TF_DIR }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: ./${{ env.TF_DIR }}
        run: terraform apply -input=false tfplan

