name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, uat ]
  pull_request:
    branches: [ main, dev, uat ]

jobs:
  terraform-build-deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Determine environment based on branch
      - name: Set Environment
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "uat" ]]; then
            echo "ENV=uat" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      # Terraform Init
      - name: Terraform Init
        working-directory: ./terraform_env/${{ env.ENV }}
        run: |
          terraform init -reconfigure \
            -backend-config=../../backend-config/${{ env.ENV }}.hcl

      - name: Terraform Validate
        working-directory: ./terraform_env/${{ env.ENV }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform_env/${{ env.ENV }}
        run: |
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: ./terraform_env/${{ env.ENV }}
        run: terraform apply -input=false tfplan
