name: Terraform CI/CD

on:
  push:
    branches: [ main, dev, uat, terraform_azure ]
  pull_request:
    branches: [ main, dev, uat, terraform_azure ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Terraform Format Check
      #   run: terraform fmt -check -recursive
      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init -input=false
          env:
            TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

      - name: Terraform Workspace Select
        run: terraform workspace select -or-create $GITHUB_REF_NAME

      - name: Terraform Validate
        working-directory: Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: Terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && (github.ref_name == 'dev' || github.ref_name == 'uat' || github.ref_name == 'main' || github.ref_name == 'terraform_azure')
        working-directory: Terraform
        run: terraform apply -auto-approve
