name: Terraform CI/CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  workflow_dispatch:
  push:
    branches: [ main, dev, uat ]
  pull_request:
    branches: [ main, dev, uat ]

jobs:
  terraform-build-deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Determine environment based on branch
      - name: Resolve Terraform Environment
        run: |
          # 1. Determine the environment name
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            ENV="prod"
          elif [[ "${{ github.ref_name }}" == "uat" ]]; then
            ENV="uat"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            ENV="dev"
          else
            echo "Unsupported branch: ${{ github.ref_name }}"
            exit 1
          fi

          # 2. Export both to GITHUB_ENV so later steps can see them
          echo "TF_ENV=$ENV" >> $GITHUB_ENV
          echo "TF_DIR=terraform_env/$ENV" >> $GITHUB_ENV



      # Terraform Init
      - name: Terraform Init
        working-directory: ./${{ env.TF_DIR }}
        run: terraform init -reconfigure -backend-config=../../backend-config/${{ env.TF_ENV }}.hcl

      - name: Terraform Plan
        working-directory: ./${{ env.TF_DIR }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: ./${{ env.TF_DIR }}
        run: terraform apply -input=false tfplan


