name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, uat, terraform_azure ]
  pull_request:
    branches: [ main, dev, uat, terraform_azure ]

jobs:
  terraform-build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create TF State Infrastructure if not exists
              run: |
                RG_NAME="tfstate-rg"
                STORAGE_ACCOUNT_NAME="tfstateuat8a9b" # Use a fixed, unique name here
                LOCATION="Southeast Asia"
                CONTAINER_NAME="tfstateuat6d9a"

                # 1. Check if the Resource Group already exists
                RG_EXISTS=$(az group exists --name $RG_NAME)

                if [ "$RG_EXISTS" == "true" ]; then
                  echo "Infrastructure already exists. Skipping creation."
                else
                  echo "Infrastructure not found. Starting creation..."

                  # Create Resource Group
                  az group create --name "$RG_NAME" --location "$LOCATION"

                  # Create Storage Account
                  az storage account create \
                    --name "$STORAGE_ACCOUNT_NAME" \
                    --resource-group "$RG_NAME" \
                    --location "$LOCATION" \
                    --sku Standard_LRS

                  # Create Blob Container
                  az storage container create \
                    --name "$CONTAINER_NAME" \
                    --account-name "$STORAGE_ACCOUNT_NAME"
                  
                  echo "Infrastructure successfully created."
                fi

      - name: Terraform Init
        id: init
        run: |
          terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && (github.ref_name == 'dev' || github.ref_name == 'uat' || github.ref_name == 'main' || github.ref_name == 'terraform_azure')
        run: terraform apply -auto-approve
